version: '3.5'

services:
  fboxoldsignalrserver:
    image: docker.flexem.com/flexem-fbox/fbox.oldsignalrserver:latest
    restart: always
    extra_hosts: 
      - "localhost:192.168.100.151"
    ports:
     - "5001:80"
    environment:
      AllowOrigins__0: http://localhost:39801
      AppSettings__ServerID: 0
      AppSettings__IdServerUrl: http://localhost:58491/core
      AppSettings__DisableSignalRServerSentEvents: "false"
      AppSettings__DisableSignalRWebSockets: "false"
      AppSettings__SignalRKeepAliveTime: 40
      AppSettings__SignalRDisconnectTimeout: 120
      AppSettings__Kafka__Brokers: localhost:9092
      AppSettings__Kafka__TopicPrefix: fboxlocal.
      AppSettings__Kafka__GroupId: fbox.signalr.push
      AppSettings__Kafka__FboxSubTopic: fbox.data.sub
      AppSettings__Redis__EndPoints: localhost:6379
      AppSettings__Redis__Database: 0