version: '3.5'
services:
  redis:
    container_name: redis
    image: bitnami/redis:5.0
    restart: always
    environment:
      # For dev only
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=Ini5jORmWL
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - '/opt/redis:/bitnami/redis/data'
      - '/opt/redis/redis.conf:/opt/bitnami/redis/etc/redis.conf'

networks:
  default:
    external: true
    name: cluster