version: '3'
services:
  ssr:
    container_name: ssr
    image: chaldea/ssr
    restart: always
    volumes:
     - /opt/ssr/config.json:/etc/shadowsocks/config.json
    ports:
     - "38388:8388"

networks:
  default:
    external: true
    name: cluster