version: '3.5'
services:
  ssr:
    container_name: ssr
    image: chaldea/ssr
    restart: always
    network_mode: host
    environment:
      SSR_SERVER_PORT: 8388
      SSR_PASSWORD: bBrJHLGZJLXZTCpTTfdM5qkrFRWr9ZJCMz91B1MVusv5jFxyu1
      SSR_METHOD: none
      SSR_PROTOCOL: auth_chain_d
      SSR_OBFS: tls1.2_ticket_auth
      SSR_OBFS_PARAM: baidu.com