version: '3.5'
services:
  emqx:
    container_name: emqx
    # image: emqx/emqx:4.3.6
    image: emqx/emqx:4.3.10
    restart: always
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_etc:/opt/emqx/etc
      - emqx_log:/opt/emqx/log
    # volumes:
    #   - /opt/emqxv4/data:/opt/emqx/data
    #   - /opt/emqxv4/log:/opt/emqx/log
    #   - /opt/emqxv4/etc:/opt/emqx/etc

volumes: 
  emqx_data:
  emqx_etc:
  emqx_log:

networks:
  default:
    external: true
    name: cluster