version: "3.5"
services: 
 npc:
  container_name: npc
  image: chaldea/npc
  restart: always
  environment:
    SERVER_ADDR: 192.168.50.151:18024
    CONN_TYPE: tcp
    VKEY: uqghnu88n51zkmlg

# networks:
#   default:
#     external: true
#     name: cluster