version: "3.5"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana/data:/var/lib/grafana
      # - /opt/grafana/conf:/etc/grafana

# volumes:
#   grafana_data:
#   grafana_conf:
