version: "3.5"

services:
  platform:
    container_name: platform
    image: docker.flexem.com/flexem/platform-web:1.0.1.24-6a8bac
    restart: always
    ports:
      - "8080:80"
    environment:
      PLATFORM_BASEURL: https://qa.fbox.flexem.net

networks:
  default:
    external: true
    name: cluster