apiVersion: v1
kind: Secret
metadata:
  name: {{ template "joplin.fullname" . }}
  labels:
    app: {{ template "joplin.name" . }}
    chart: {{ template "joplin.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{.Values.env.POSTGRES_PASSWORD | trimAll "\"" | b64enc | quote}}