version: '3.5'

services:
  dotnet:
    build: .
    image: chaldea/dotnet:6.0-node16
    # image: mcr.microsoft.com/dotnet/aspnet:6.0
    container_name: dotnet
    entrypoint: tail -f /dev/null
    volumes:
      - /root/projects/chaldea/dotnet:/projects

networks:
 default:
   external: true
   name: cluster
