# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
     - /opt/postgresql/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
