version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    user: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
     - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@root.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
      - /opt/postgresql/admin:/var/lib/pgadmin
    ports:
      - 8082:80

networks:
  default:
    external: true
    name: cluster
