version: '3.5'
services:
  postgres:
    container_name: postgres
    image: postgres
    user: postgres
    restart: always
    ports: 
      - 5432:5432
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  # pgadmin4:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@root.com
  #     PGADMIN_DEFAULT_PASSWORD: 123456
  #   volumes:
  #     - /opt/docker/postgresql/admin/conf:/root/.pgadmin
  #     - /opt/docker/postgresql/admin/data:/var/lib/pgadmin/storage
  #   ports:
  #     - 8082:80

networks:
  default:
    external: true
    name: cluster
