version: '3.5'

services:
  simmanager:
    container_name: simmanager
    image: docker.flexem.com/flexem-fbox/fbox.simmanager:1.0.0.59-1e8b28
    restart: always
    ports:
     - "9004:80"
    environment:
      ConnectionStrings__Connection: User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=fbsim;Pooling=true;
      AppSettings__IdSvrAuthority: http://192.168.50.151:58491/core
      AppSettings__Kafka__Brokers: kafka:9092
      AppSettings__Kafka__TopicPrefix: fboxlocal.

networks:
  default:
    external: true
    name: cluster