version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    restart: always
    volumes:
     - rancher_data:/var/lib/rancher
    ports:
     - "80:80"
     - "443:443"

volumes:
  rancher_data: