version: "3.5"

services:
  firmware-manager:
    container_name: firmware-manager
    image: docker.flexem.com/flexem/firmware-manager:1.0.0.49-dea9d7
    restart: always
    ports:
      - "9002:9002"
    environment:
        ConnectionStrings__Firmware: server=192.168.50.151;port=5432;user id=postgres;password=postgres;database=firmware
        AuthServer__Authority: http://192.168.50.151:58491/core
        AuthServer__ClientId: platform
        AuthServer__ClientSecret: platform
        BoxManager__Url: http://appsvr:39901
        HmiManager__DownloadUrl: http://192.168.50.151:9000/public/firmware/hmi/
        Redis__EndPoints: redis:6379
        Redis__DataBase: 6
        Mqtt__Host: emqx
        Mqtt__Port: 1883
        Mqtt__ClientId: firmware
        Mqtt__UserName: admin
        Mqtt__Password: 123456
        Minio__Endpoint: minio:9000
        Minio__AccessKey: admin
        Minio__SecretKey: 426gcHKN1B
        Kafka__BootstrapServers: kafka:9092
        Kafka__TopicPrefix: fboxlocal.
        
networks:
  default:
    external: true
    name: cluster