---
    accessKey: "xxxxx"
    secretKey: "xxxxx"
    persistence:
      enabled: true
      storageClass: local-path
      size: 1000Gi
    service:
      type: NodePort
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - oss.chaldea.cn
      tls:
        - secretName: wildcard-chaldea-cn-tls
          hosts:
            - '*.chaldea.cn'
    nodeSelector:
      storage: nas