---
# Source: firmware-manager/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: firmware-manager
  labels:
    app.kubernetes.io/name: firmware-manager
    helm.sh/chart: firmware-manager-0.1.0
    app.kubernetes.io/instance: preview
    app.kubernetes.io/managed-by: Tiller
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: firmware-manager
    app.kubernetes.io/instance: preview
---
# Source: firmware-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firmware-manager
  labels:
    app.kubernetes.io/name: firmware-manager
    helm.sh/chart: firmware-manager-0.1.0
    app.kubernetes.io/instance: preview
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: firmware-manager
      app.kubernetes.io/instance: preview
  template:
    metadata:
      labels:
        app.kubernetes.io/name: firmware-manager
        app.kubernetes.io/instance: preview
    spec:
      containers:
        - name: firmware-manager
          image: docker.flexem.com/flexem/firmware-manager:1.0.0.12-defbd0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9002
              protocol: TCP
          env:
            - name: ConnectionStrings__Firmware
              value: "server=flexem-test.pg.rds.aliyuncs.com;port=1433;user id=fm;password=NOco50qD1U;database=fm;"
            - name: AuthServer__Authority
              value: "http://account.fbox360.cn/core"
            - name: AuthServer__ClientId
              value: "hzwz"
            - name: AuthServer__ClientSecret
              value: "91d1c5a413d9e8f4b01e8a105d949d2e"
            - name: HmiManager__DownloadUrl
              value: "http://oss.fbox360.cn/public/firmware/hmi/"
            - name: BoxManager__Url
              value: "http://app.fbox360.cn"
            - name: Redis__EndPoints
              value: "redis-headless.redis:6379"
            - name: Redis__DataBase
              value: "6"
            - name: Mqtt__Host
              value: "emqx.mqtt"
            - name: Mqtt__Port
              value: "1883"
            - name: Mqtt__ClientId
              value: firmware
            - name: Mqtt__UserName
              value: "admin"
            - name: Mqtt__Password
              value: "123456"
            - name: Minio__Endpoint
              value: "minio.minio:9000"
            - name: Minio__AccessKey
              value: "ltS8Sfj4qk"
            - name: Minio__SecretKey
              value: "CnQxJl2t7X5f963B5RYL8D9bkxTTBDJ1kdJ2Rcqs"
            - name: Kafka__BootstrapServers
              value: "172.18.138.232:9092"
            - name: Kafka__TopicPrefix
              value: "fboxstage."
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 128Mi