---
apiVersion: v1
kind: Service
metadata:
  name: platform-web
  labels:
    app.kubernetes.io/name: platform-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: platform-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-web
  labels:
    app.kubernetes.io/name: platform-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: platform-web
    spec:
      containers:
        - name: platform-web
          image: docker.flexem.com/flexem/platform-web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PLATFORM_BASEURL
              value: https://platform.flexem.net
