version: '3.5'

services:
  webapp:
    container_name: webapp
    #image: docker.flexem.com/flexem-fbox/fbox.webapp:1.76.6-genyun
    image: docker.flexem.com/flexem-fbox/fbox.webapp:1.0.1.301-d6aaa2
    ports:
     - "39801:80"
    restart: always
    environment:
      asApiUrl: http://192.168.50.151:30000/
      asPushUrl: http://192.168.50.151:30000/push/client
      idSvrUrl: http://192.168.50.151:30000/
      fsApiUrl: http://192.168.50.151:30000/api/
      hsApiUrl: http://fbhsd.fbox360.net/api/

networks:
  default:
    external: true
    name: cluster