---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin4-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4-service
  labels:
    app.kubernetes.io/name: pgadmin4
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pgadmin4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin4-deployment
  labels:
    app.kubernetes.io/name: pgadmin4
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgadmin4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgadmin4
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@flexem.cn
            - name: PGADMIN_DEFAULT_PASSWORD
              value: 1qaz!QAZ
          volumeMounts:
            - mountPath: /root/.pgadmin
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgadmin4-pvc
