version: '3.5'
services:
  connector:
    container_name: connector
    image: docker.flexem.com/flexem-fbox/fbox.connector:1.3.3.26-86ea59
    restart: always
    volumes:
     - /opt/fbox/conn/commands.json:/app/commands.json
    ports:
     - "7157:7157"
     - "7257:7257"
     - "8063:8063"
    environment:
      AppSettings__Discover: etcd
      AppSettings__UseBoxHeadParse: "true"
      AppSettings__OffTaskMsgPushToCS: "true"
      AppSettings__Etcd__Prefix: fboxlocal
      AppSettings__Etcd__Connection: http://192.168.50.151
      AppSettings__Etcd__Port: 2379
      AppSettings__Redis__EndPoints: redis:6379
      AppSettings__DumpPackets: "true"
      Kafka__GroupId: "fbox-conn.server"
      Kafka__BootstrapServers: "kafka:9092"
      Kafka__BoxMessageConsumerCount: "4"
      Kafka__TopicPrefix: "fboxlocal."
      Connector__Endpoints__0__AdvertisedIP: 192.168.50.151
      Connector__Endpoints__0__AdvertisedPort: 7157

networks:
  default:
    external: true
    name: cluster