---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: mqtt-tpc
      protocol: TCP
      name: mqtt-tpc
    - port: 8083
      targetPort: mqtt-ws
      protocol: TCP
      name: mqtt-ws
    - port: 8084
      targetPort: mqtt-wss
      protocol: TCP
      name: mqtt-wss
    - port: 8883
      targetPort: mqtt-ssl
      protocol: TCP
      name: mqtt-ssl
    - port: 18083
      targetPort: mqtt-dashboard
      protocol: TCP
      name: mqtt-dashboard
  selector:
    app.kubernetes.io/name: emqx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-data-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-etc-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  labels:
    app.kubernetes.io/name: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt-tpc
              containerPort: 1883
              protocol: TCP
            - name: mqtt-ws
              containerPort: 8083
              protocol: TCP
            - name: mqtt-wss
              containerPort: 8084
              protocol: TCP
            - name: mqtt-ssl
              containerPort: 8883
              protocol: TCP
            - name: mqtt-dashboard
              containerPort: 18083
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/emqx/data
              name: data
            - mountPath: /opt/emqx/etc
              name: etc
      volumes:
        - name: data
          persistentVolumeClaim: 
            claimName: emqx-data-pvc
        - name: etc
          persistentVolumeClaim: 
            claimName: emqx-etc-pvc
