---
# Source: webhook-alidns/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: webhook-alidns:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: webhook-alidns
    chart: webhook-alidns-0.1.0
    release: webhook-alidns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: webhook-alidns
    namespace: cert-manager