version: "3.5"

services: 
 mssql:
  container_name: mssql
  image: mcr.microsoft.com/mssql/server:2017-latest
  restart: always
  environment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: "Bu32Xdgu"
  ports:
    - "1433:1433"
  volumes:
    - /opt/mssql/data:/var/opt/mssql/data

networks:
  default:
    external: true
    name: cluster