version: '3.5'

services:
  subscribeapi:
    container_name: subscribeapi
    image: docker.flexem.com/flexem-fbox/fbox.subscribeapi:1.0.0.5314-ca55ba
    ports: 
     - "50001:80"
    restart: always
    environment:
      ConnectionStrings__Connection: "server=postgres;port=5432;user id=postgres;password=postgres;database=subpushdev"
      AppSettings__AppCode: api1
      AppSettings__IdSvrAuthority: http://192.168.50.151:58491/core/
      AppSettings__IdSvrSecret: secret
      AppSettings__SubscribeKafka__Brokers: kafka:9092
      AppSettings__SubscribeKafka__Topic: fboxlocal.fbox.data.sub
      AppSettings__ConfigKafka__Brokers: kafka:9092
      AppSettings__ConfigKafka__Topic: fboxlocal.fbox.subscribe.config
      AppSettings__Redis__EndPoints: redis:6379
      AppSettings__Redis__Database: 0
      AppSettings__StatisticsKeys__DmonDataKey: fboxlocal.fbox.dmon.data
      AppSettings__StatisticsKeys__AlarmDataKey: fboxlocal.fbox.alarm.data
      AppSettings__StatisticsKeys__HdataDataKey: fboxlocal.fbox.hdata.data

networks:
  default:
    external: true
    name: cluster