version: '3.5'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.2
    restart: always
    volumes: 
      - /opt/kafka/zookeeper:/var/lib/zookeeper
    ports: 
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:5.4.2
    restart: always
    volumes: 
      - /opt/kafka/data:/var/lib/kafka/data
      - /opt/kafka/config:/etc/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://192.168.50.151:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  default:
    external: true
    name: cluster
