version: '3.5'

services:
  # migrate:
  #   container_name: identity-migrate
  #   image: docker.flexem.com/flexem/idsrv.migration:1.2.0
  #   environment:
  #     ConnectionStrings__AdminConnection: "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=fxid;Pooling=true;"
  #   entrypoint: dotnet Flexem.IdentityServer4.EFMigration.dll /migrate

  identity:
    container_name: identity
    image: docker.flexem.com/flexem-fbox/fbox.idserver:1.2.1.46-d9c14b
    restart: always
    ports: 
     - "58491:80"
     - "58492:443"
    environment:
      UseDB: postgre
      ConnectionStrings__AdminConnection: "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=fxid;Pooling=true;"
      IdentityServer__Authority: "http://192.168.50.151:58491"
      # IdentityServer__Authority: "https://openapi.flexem.net"
  
  Flexem.IdentityServer4.Admin:
    image: docker.flexem.com/flexem-fbox/fbox.idadmin:2.0.0.34-86ea59
    restart: always
    ports: 
     - "58493:80"
     - "58494:443"
    environment:
      UseDB: postgre
      ConnectionStrings__AdminConnection: "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=fxid;Pooling=true;"
      AdminConfiguration__IdentityAdminBaseUrl: "http://192.168.50.151:58493"
      AdminConfiguration__IdentityAdminRedirectUri: "http://192.168.50.151:58493/signin-oidc"
      AdminConfiguration__IdentityServerBaseUrl: "http://192.168.50.151:58491/core"

networks:
  default:
    external: true
    name: cluster