---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app.kubernetes.io/name: mqtt
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: 9001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mqtt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  labels:
    app.kubernetes.io/name: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:1.6.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: http
              containerPort: 9001
              protocol: TCP
