version: "3.5"
services: 
 nps:
  container_name: nps
  image: chaldea/nps
  restart: always
  network_mode: host
  # ports:
  #   - "1180:80"
  #   - "11443:443"
  #   - "18080:8080"
  #   - "18024:8024"
  volumes:
    - /opt/nps/data:/nps/data
  environment:
    HTTP_PROXY_PORT: 1180
    HTTPS_PROXY_PORT: 11443
    WEB_USERNAME: test
    WEB_PASSWORD: 123456
    WEB_PORT: 18080
    BRIDGE_PORT: 18024

# networks:
#   default:
#     external: true
#     name: cluster