version: '3.5'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - /opt/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1qaz!QAZ

networks:
  default:
    external: true
    name: cluster