version: '3.5'
services:
  etcd:
    container_name: etcd
    image: bitnami/etcd:3.4
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - /opt/etcd:/bitnami

networks:
  default:
    external: true
    name: cluster