version: '3'
services:
  commsvr:
    image: docker.flexem.com/flexem-fbox/fbox.commsvr:1.0.0.3647-95b334
    volumes:
     - /opt/fbox/fbcs/firmware:/app/firmware
     - /opt/fbox/fbcs/LocalDb:/app/LocalDb
     - /opt/fbox/fbcs/log:/app/log
    ports:
     - "39902:39902"
    environment:
      AppSettings__IdServerUrl: "http://192.168.50.150:58491/core/"
      AppSettings__CsAppServerUrl: "http://192.168.50.150:39901/api/cs/"
      AppSettings__CsAppServerPushUrl: "http://192.168.50.150:39901/push/client/"
      AppSettings__RsAppServerUrl: "http://192.168.50.150:39901/api/rs/"
      AppSettings__RsAppServerPushUrl: "http://192.168.50.150:39901/push/client/"
      AppSettings__SmsServerUrl: "http://127.0.0.1:60004/api/sms/"
      AppSettings__DisableSms: "true"
      AppSettings__FirmwareServerUrl: "	http://defs.flexem.net/"
      AppSettings__MaxPreloadedDataSources: "20000"
      AppSettings__MaxPreloadedDmonDefs: "20000"
      AppSettings__MaxPreloadedAlarmDefs: "20000"
      AppSettings__MaxPreloadedContacts: "20000"
      ConnectionStrings__Provider: PgSql
      ConnectionStrings__MsSql: "Server=192.168.50.150;Database=fbcs;Trusted_Connection=True;"
      ConnectionStrings__PgSql: "server=192.168.50.150;database=fbcs;port=5432;user id=postgres;password=123qwe!@#;"
      Cassandra__ConnectionString: "Contact Points=192.168.50.77"
      Cassandra__Port: "34622"
      Kafka__BootstrapServers: "192.168.50.150:9092"
      Kafka__TopicPrefix: "fboxlocal."