---
    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - grafana.chaldea.cn
      tls:
        - secretName: wildcard-chaldea-cn-tls
          hosts:
            - '*.chaldea.cn'
    nodeSelector:
      storage: database