version: '3.7'

services:
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    volumes:
      - /opt/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: 426gcHKN1B
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default:
    external: true
    name: cluster