tls.crt
-----BEGIN CERTIFICATE-----
MIIEmzCCA4OgAwIBAgIJAJAGQlMmC0kyMA0GCSqGSIb3DQEBBQUAMIGPMQswCQYD
VQQGEwJVUzERMA8GA1UECBMIQ29sb3JhZG8xEDAOBgNVBAcTB0JvdWxkZXIxFDAS
BgNVBAoTC0V4YW1wbGVDb3JwMQswCQYDVQQLEwJJVDEWMBQGA1UEAxQNKi5leGFt
cGxlLmNvbTEgMB4GCSqGSIb3DQEJARYRYWRtaW5AZXhhbXBsZS5jb20wHhcNMTYx
MDI0MjEwOTUyWhcNMTcxMDI0MjEwOTUyWjCBjzELMAkGA1UEBhMCVVMxETAPBgNV
BAgTCENvbG9yYWRvMRAwDgYDVQQHEwdCb3VsZGVyMRQwEgYDVQQKEwtFeGFtcGxl
Q29ycDELMAkGA1UECxMCSVQxFjAUBgNVBAMUDSouZXhhbXBsZS5jb20xIDAeBgkq
hkiG9w0BCQEWEWFkbWluQGV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAtuJ9mww9Bap6H4NuHXLPzwSUdZi4bra1d7VbEBZYfCI+Y64C
2uu8pu3aU5sauMbD97jQaoyW6G98OPreWo8oyfndIctErlnxjqzU2UTV7qDTy4nA
5OZeoReLfeqRxllJ14Via5QdgywGLhE9jg/c7e4YJznh9KWY2qcVxDuGD3iehsDn
aNzV4WF9cIfms8zwPvONNLfsAmw7uHT+3bK13IIhx27fevquVpCs41P6psu+VLn2
5HDy41thBCwOL+N+albtfKSqs7LAs3nQN1ltzHLvy0a5DhdjJTwkPrT+UxpoKB9H
4ZYk1+EDt7OPlhyo3741QhN/JCY+dJnALBsUjQIDAQABo4H3MIH0MB0GA1UdDgQW
BBRpeW5tXLtxwMroAs9wdMm53UUILDCBxAYDVR0jBIG8MIG5gBRpeW5tXLtxwMro
As9wdMm53UUILKGBlaSBkjCBjzELMAkGA1UEBhMCVVMxETAPBgNVBAgTCENvbG9y
YWRvMRAwDgYDVQQHEwdCb3VsZGVyMRQwEgYDVQQKEwtFeGFtcGxlQ29ycDELMAkG
A1UECxMCSVQxFjAUBgNVBAMUDSouZXhhbXBsZS5jb20xIDAeBgkqhkiG9w0BCQEW
EWFkbWluQGV4YW1wbGUuY29tggkAkAZCUyYLSTIwDAYDVR0TBAUwAwEB/zANBgkq
hkiG9w0BAQUFAAOCAQEAcGXMfk8NZsB+t9KBzl1Fl6yIjEkjHO0PVUlEcSD2B4b7
PxnMOjdmgPrauHb9unXEaL7zyAqaD6tbXWU6RxCAmgLajVJNZHOw45N0hrDkWgB8
EvZtQ56ammwC1qIhAiA6390D3Csex7gL6nJo7kbr1YWUG3zIvoxdz8YDrZNeWKLD
pRvWen0lMbpjIRP4XZsnC45C9gVXdh3LRe1+wyQq6h9QPiloxmD6NpE9imTOn2A5
/bJ3VKIzAMudeU6kpyYlJBzdG1uaHTjQOWosGiweCKVUXF6UtisVddrxQth6ENyW
vIFqaZx84+DlSCc93yfk/GlBt+SKG46zEHMB9hqPbA==
-----END CERTIFICATE-----

tls.key
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAtuJ9mww9Bap6H4NuHXLPzwSUdZi4bra1d7VbEBZYfCI+Y64C
2uu8pu3aU5sauMbD97jQaoyW6G98OPreWo8oyfndIctErlnxjqzU2UTV7qDTy4nA
5OZeoReLfeqRxllJ14Via5QdgywGLhE9jg/c7e4YJznh9KWY2qcVxDuGD3iehsDn
aNzV4WF9cIfms8zwPvONNLfsAmw7uHT+3bK13IIhx27fevquVpCs41P6psu+VLn2
5HDy41thBCwOL+N+albtfKSqs7LAs3nQN1ltzHLvy0a5DhdjJTwkPrT+UxpoKB9H
4ZYk1+EDt7OPlhyo3741QhN/JCY+dJnALBsUjQIDAQABAoIBAHkLxdkGq6kBYd1T
z2E8aaD6xgxjrcbRtaBq77/hGmXnAGZXeVpO50mRao0lvvUH0hM3RvMO5J8pkw3f
taY41OWCNMO2V1oS/BfT+vlnXzWXSzePkJWwiHeVLuWDiULAPGiixzavDS2RyPFa
xeQuSatNiL0FybF0nYwzROvh/eRkcJVrQfVnuMfzQd8h236eoU1SpzRxR6Inl+9P
MsTvZnNBf9wAVpZ9sSL2puWX7HcR2Ugznh03YYFItkCfwmn+DlGokOXXpU3o6if9
THzpexwnmRVJagDo9m9PwkxAz09o4qq1trhSX5Sju+Lr4Ro8x9o+WuAuVupoIGwL
1elxDEECgYEA75ZXjuzsIGOO2F9M+raQPqs+DvvDJsCx2ftnvMVYRJqYbhkzbzlU
0HpBVy76a7ZazRlawtFgyc2ZrA8i3Aw+rzwZPrSIycbx/gQWnG6elQucAEUgW84M
GRmxJPif8dP5LlewQjQcPRpeZ139X82kxdRHGfkZlpyWBqKj0SXLQHECgYEAw2nA
mEWud3dRojnsnqNb0eawEPT+o0cgdrhCP96P+ZDzCaqDTnVJWmOyeqFY5yWRHFN/
slHWSiSEAcEtXg+9hiLsDWtuOw8Tg627ek8HuQKLokVXATXmMdoq9drAoH5NaWiD
dRcwDSa/jhH7tYWXJd08VJT6RIuO/1Vil0mlI90CgYEAoil6Hg0STWHVX3IxokhL
HX++Q1n4XpRyTH4zWruf4N9aaLq564A8fdchvqbXbGxCzStqGQ6qmiyE5MZh69qF
2wmsdJqxMxFq3Wla/IqK34q6Dhy7qCewXJTdJ474gy/cKpfDfyvSKTFd0Ez3oA6K
hjQF4/iMbzqQ+PDAPGF+TqECgYBd5bvgr2L1DsWQISs80xw00Rd7Hm4ZAP1tbn6O
+B/QeMD/vQpZMexsXYmOeWchsqB2rvymL8K7X656tVtaXk/gW3l3vU57XHQxCtMS
I1V/peR4tb7n2wFgpQeNmW6D8Ay8gLbiFaFGQH89AhEkGSwWyqbJschMFY9By8KT
FZUflQKBgEwW2dUJNdBLysrp8NLMUlkufrqnYiQ3SAHh4VsZH5Mu41nyb/y5E21n
2NywymXdeouIpVcqIUMyt/qJFhHpRMyQ2ZKOGD2XnXhCMVTe/AP42hwox6m6BFiB
ozfEkl0jNnfdDr6k/Zv2T5NqsilZErABVF90Jk7mPPHkD6GVLQBx
-----END RSA PRIVATE KEY-----


LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZUakNDQkRhZ0F3SUJBZ0lTQTZXZjdQb3ZqSTBlNUpNRXNWakE5cWVoTUEwR0NTcUdTSWIzRFFFQkN3VUEKTUVveEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1TTXdJUVlEVlFRRApFeHBNWlhRbmN5QkZibU55ZVhCMElFRjFkR2h2Y21sMGVTQllNekFlRncweU1EQXpNakl3TlRVMU1qWmFGdzB5Ck1EQTJNakF3TlRVMU1qWmFNQmN4RlRBVEJnTlZCQU1NRENvdVkyaGhiR1JsWVM1amJqQ0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQVUg2cDRIaXBPYkcwOTdrbDdnYWlxK0p0K2M3MUNYaWlxQwpid2w4d0p4SUwvMUgzeWlGMlJPSlQzc0kyUHZzVUtHZkRDbTZLYUgvWXc4Y0hDcW9HRU05c3Q2U0MwYndBbzFHClpPcmV5NUZyM0UxV0VWdTdIb09aQWx6ellSa0VIdnJIOE5reUY1NXhRNlZ2ZUJHdk5WYU5aUXJoZEk1NDErdnAKTEZxRDdZK29WdFU3aVY5RnZzRFRHY3pEak5RR25LaHJubVg0TGVvOG9pejhXZGxsVS9mOUNYa1FtZXFzL2xUVQpUV0QxVTZRRktIT0VqSnIvOVZ0ZEpNRmxmSGlLSXRNYUVMTmpkc2c4dng3NzdHSUtlQ1FxcXU0UmMvZkRKb3RWClVFa3Jtb3JZTVJGVGdac1AxeDE5dnF6S0NxNVpoRW9YY1FTKzlEejFqRFNVQUUxWVJRTUNBd0VBQWFPQ0FsOHcKZ2dKYk1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSApBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVVGR0FDalJKUGhUYnI4Zys2U1hKMUpZeGp0cXN3Ckh3WURWUjBqQkJnd0ZvQVVxRXBxWXdSOTNicm0wVG0zcGtWbDcvT283S0V3YndZSUt3WUJCUVVIQVFFRVl6QmgKTUM0R0NDc0dBUVVGQnpBQmhpSm9kSFJ3T2k4dmIyTnpjQzVwYm5RdGVETXViR1YwYzJWdVkzSjVjSFF1YjNKbgpNQzhHQ0NzR0FRVUZCekFDaGlOb2RIUndPaTh2WTJWeWRDNXBiblF0ZURNdWJHVjBjMlZ1WTNKNWNIUXViM0puCkx6QVhCZ05WSFJFRUVEQU9nZ3dxTG1Ob1lXeGtaV0V1WTI0d1RBWURWUjBnQkVVd1F6QUlCZ1puZ1F3QkFnRXcKTndZTEt3WUJCQUdDM3hNQkFRRXdLREFtQmdnckJnRUZCUWNDQVJZYWFIUjBjRG92TDJOd2N5NXNaWFJ6Wlc1agpjbmx3ZEM1dmNtY3dnZ0VDQmdvckJnRUVBZFo1QWdRQ0JJSHpCSUh3QU80QWRRRG5Fdkt3TjM0YVl2dU95UXhoCmhQSHFlemZMVmgwUkpsdno0UE5MOGtGVWJnQUFBWEVCQmw0c0FBQUVBd0JHTUVRQ0lCTnEwNUs0TnhVMkw4QlcKcnVCbGV0N1dpN0VRZ2R1UVp6VFV6bjJpWWg4UUFpQXEzaUwvRWw3c3RqTElMMG1YSkE0UW9jSGh0ZVFCR3BudApOT01WbWtHZVh3QjFBTEllQmN5TG9zMktJRTZIWnZrcnVZb2xJR2RyMnZwdzU3SkpVeTN2aTVCZUFBQUJjUUVHClhrY0FBQVFEQUVZd1JBSWdPZWhOWkhOM2EwNy9vWkpjbkZlOG9vWFE1VmpmbE9VckNoM29BSHM2S1JnQ0lBLy8KWC9NN0tHajM3UnAvVW1UaTRTOTMzVlZCVE5pK055ZGtic1NSUW93Z01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUE0WWQ4SFJQVzFqbVVBbEVZajZaU1NMT1FTMGpuZE0zb2FkQ2lrQlJ3bjBjOUV1Vkt6RjFRODE5TDJJc28rCkJDRzRFZ3cvb2VNODZZMkF4SnhnS01CMnpibEtjbE84K0RmclgrYThrZC9rN2xoaDAwQmpwS2t2WHY5dkNrVkkKc2NSemM2UEE1U0t3aWo5UGJjbmlVOFJrUGpXWHZla0pwejVhRWNldWNJTGwveER4b0RWQ05oOUxkVjZIaEdibwpjUUh1Uk0ycXNQT1hXZ254RTVFMURaYUxaNUViZU01ejhwNW5uekdOZFgxUmNYZFhaTDRMcWR6V1c2UVdTSWZoCk1xLzhGcDExSExES21UY3lTMzRFUmNXWEJvaENVaks3YkNmTnhMc1BXdmRnUUV2c3BMeXBYa0ZPYVFlU3lXZW8Kb3dLaUtMY1M1NXhjOHA2WU5Rd3kxVkFiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVrakNDQTNxZ0F3SUJBZ0lRQ2dGQlFnQUFBVk9GYzJvTGhleW5DREFOQmdrcWhraUc5dzBCQVFzRkFEQS8KTVNRd0lnWURWUVFLRXh0RWFXZHBkR0ZzSUZOcFoyNWhkSFZ5WlNCVWNuVnpkQ0JEYnk0eEZ6QVZCZ05WQkFNVApEa1JUVkNCU2IyOTBJRU5CSUZnek1CNFhEVEUyTURNeE56RTJOREEwTmxvWERUSXhNRE14TnpFMk5EQTBObG93ClNqRUxNQWtHQTFVRUJoTUNWVk14RmpBVUJnTlZCQW9URFV4bGRDZHpJRVZ1WTNKNWNIUXhJekFoQmdOVkJBTVQKR2t4bGRDZHpJRVZ1WTNKNWNIUWdRWFYwYUc5eWFYUjVJRmd6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBbk5NTThGcmxMa2UzY2wwM2c3Tm9ZekRxMXpVbUdTWGh2YjQxOFhDU0w3ZTRTMEVGCnE2bWVOUWhZN0xFcXhHaUhDNlBqZGVUbTg2ZGljYnA1Z1dBZjE1R2FuL1BRZUdkeHlHa09sWkhQL3VhWjZXQTgKU014K3lrMTNFaVNkUnh0YTY3bnNIamNBSEp5c2U2Y0Y2czVLNjcxQjVUYVl1Y3Y5YlR5V2FOOGpLa0tRRElaMApaOGgvcFpxNFVtRVVFejlsNllLSHk5djZEbGIyaG9uemhUK1hocSt3M0JydmF3MlZGbjNFSzZCbHNwa0VObldBCmE2eEs4eHVRU1hndm9wWlBLaUFsS1FUR2RNRFFNYzJQTVRpVkZycW9NN2hEOGJFZnd6Qi9vbmt4RXowdE52amoKL1BJemFyazVNY1d2eEkwTkhXUVdNNnI2aENtMjFBdkEySDNEa3dJREFRQUJvNElCZlRDQ0FYa3dFZ1lEVlIwVApBUUgvQkFnd0JnRUIvd0lCQURBT0JnTlZIUThCQWY4RUJBTUNBWVl3ZndZSUt3WUJCUVVIQVFFRWN6QnhNRElHCkNDc0dBUVVGQnpBQmhpWm9kSFJ3T2k4dmFYTnlaeTUwY25WemRHbGtMbTlqYzNBdWFXUmxiblJ5ZFhOMExtTnYKYlRBN0JnZ3JCZ0VGQlFjd0FvWXZhSFIwY0RvdkwyRndjSE11YVdSbGJuUnlkWE4wTG1OdmJTOXliMjkwY3k5awpjM1J5YjI5MFkyRjRNeTV3TjJNd0h3WURWUjBqQkJnd0ZvQVV4S2V4cEhzc2NmcmI0VXVRZGYvRUZXQ0ZpUkF3ClZBWURWUjBnQkUwd1N6QUlCZ1puZ1F3QkFnRXdQd1lMS3dZQkJBR0MzeE1CQVFFd01EQXVCZ2dyQmdFRkJRY0MKQVJZaWFIUjBjRG92TDJOd2N5NXliMjkwTFhneExteGxkSE5sYm1OeWVYQjBMbTl5WnpBOEJnTlZIUjhFTlRBegpNREdnTDZBdGhpdG9kSFJ3T2k4dlkzSnNMbWxrWlc1MGNuVnpkQzVqYjIwdlJGTlVVazlQVkVOQldETkRVa3d1ClkzSnNNQjBHQTFVZERnUVdCQlNvU21wakJIM2R1dWJST2JlbVJXWHY4Nmpzb1RBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUEzVFBYRWZOaldEamRHQlg3Q1ZXK2RsYTVjRWlsYVVjbmU4SWtDSkx4V2g5S0VpazNKSFJSSEdKbwp1TTJWY0dmbDk2UzhUaWhSelp2b3JvZWQ2dGk2V3FFQm10enczV29kYXRnK1Z5T2VwaDRFWXByLzF3WEt0eDgvCndBcEl2SlN3dG1WaTRNRlU1YU1xclNERTZlYTczTWoydGNNeW81ak1kNmptZVdVSEs4c28vam9XVW9IT1Vnd3UKWDRQbzFRWXorM2RzemtEcU1wNGZrbHhCd1hSc1cxMEtYelBNVForc09QQXZleXhpbmRtamtXOGxHeStRc1JsRwpQZlorRzZaNmg3bWplbTBZK2lXbGtZY1Y0UElXTDFpd0JpOHNhQ2JHUzVqTjJwOE0rWCtRN1VOS0VrUk9iM042CktPcWtxbTU3VEgySDNlREpBa1NuaDYvRE5GdTBRZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K


LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBOVFmcW5nZUtrNXNiVDN1U1h1QnFLcjRtMzV6dlVKZUtLb0p2Q1h6QW5FZ3YvVWZmCktJWFpFNGxQZXdqWSsreFFvWjhNS2JvcG9mOWpEeHdjS3FnWVF6MnkzcElMUnZBQ2pVWms2dDdMa1d2Y1RWWVIKVzdzZWc1a0NYUE5oR1FRZStzZncyVElYbm5GRHBXOTRFYTgxVm8xbEN1RjBqbmpYNitrc1dvUHRqNmhXMVR1SgpYMFcrd05NWnpNT00xQWFjcUd1ZVpmZ3Q2anlpTFB4WjJXVlQ5LzBKZVJDWjZxeitWTlJOWVBWVHBBVW9jNFNNCm12LzFXMTBrd1dWOGVJb2kweG9RczJOMnlEeS9IdnZzWWdwNEpDcXE3aEZ6OThNbWkxVlFTU3VhaXRneEVWT0IKbXcvWEhYMityTW9LcmxtRVNoZHhCTDcwUFBXTU5KUUFUVmhGQXdJREFRQUJBb0lCQVFDbDkxUzg4Vksxbyt1ZApySTk1My90Sk5EN1VXMUhsZnA5Qko5UFowendMSHdJU1Jtb3E0bTRrUTI4b1lOZkgyMHJLRGhhSTlPVmFLc2VICjVueFZrRUhPMmEyYi84UFBxcVd2MXl4bndieVVwVUEweWNVOElzUUtVc3M4OWtTZ1V5QkFzTWk3OUtmMjA3VUUKQ3pxQ2ovQkt6YjdRM2VDNjE3TTR3VmtmZmhpY29nL05zc0JHR3Awa2xocjh6eEM4Z1oySTlCeUZJVzZ0MXJIZwpsbXlYYTl0UktqUWxnbGF0aW1hMmgwODJZQVE3ZU41K0xWOHd5V01wZWJsem1KbWZVWm1BUkw4eDJzNFI5eVJCCkNxRTNIZ3c0em9XU3lsRVJZVEc0NE9Oenk4ekpxamR2SkZDS1p0MGlQV1pmbHRiMGhDbElIblZWWFBwZ2pYY1EKSGhvR20xdHhBb0dCQVBjZ0ovdEQxbzE1WFJTYmZYb0tyTGRBR0gxZ1BucXFrc0ZOVi9EMGgvRm90UEJrb0RZTwpSMG1WbURmRVpWWFpOMDFIN2tjNmdNVXRiRHNCd1puYmsrYjhyZWtJVDU2TTBRditncjlDdjdzWm5BTzgvVWxjCm8va2s0cS85LzRHVXhxQzJlM1ZPNlEwc0E5S0puTHNsa1B5VVFkWElVaHF1WXd1dk4vQi9YSlJ0QW9HQkFQM1UKZ1BIb05NYkhFVUsxMHRtZFJBUUJHS2RzSXgrTC9SQnUxakllaTF5T1dhSkJ3KzVDZDlZVFJiR2Z3QlhQS0YxWgpsZng5NnNSdkptRkU1N3ZFUTF1VWpMVVZzdkptQ3pvY0ZkVFJncEZEcUk1NllQa1hlRC9ER1EvTk9VL3Ztb3hrCkRMUUMyQkl5dnF4L2QxSngwdTlnbnlzZ0ZZUFFuaHVLd3kwUUIva3ZBb0dBVXUxUGZWbStYYXNrT1E0VWhTZWYKM2I1OGVWWWFvVDhzRUFITVNPZEYxeFN6NHhkaFM4SnUyWnFCZ2ZVOXJCbEFIWWJOeHNreS9QZkpJZVBzKzV4YgpmVis5WEQyVnVqYTJ6N2VRV0c0bHVMdFhSMG5jRlFvcFhDbXNpREpMMDBnQmYxeTlBUmlCekJIQkZwMW5Jc1h3CmFWRzI1ZTVhM3VrMkEyM0E3OHROWGVFQ2dZQmFMa214cUlJM3JUb2dyV0RBRi9PMlNIMXQzaW1NWjd2OVBxT3oKSXM3NGowcWhMeVJoWGhRZFpyTjRLLzJld2Y3aFM1YlNJaHBxdCtLMjVEaEFxYllVcjI1ZVY5cy82NmxKZC9qNQpwNFh2L2szQWNSSks3ViszcDZVYnpCbjBvSGdVTU9laWZQQXZadi8vWVRvUGZJa29xdmRoNXdBOTJMeVRwSFU3CmFWcXIyUUtCZ0I3ZFZCRlNCQzdDU0pGOUkzQ2ZwNE9YR0ZGWit3eXFKZmZ2aE1tTWtrYkJ5eEszcFdWRG02MngKS21UL25YM1I0cXoxWld1MFh3QkRUbEtuRVk5Q0t4UG13c3NKbDEyelBxWEJJVHRiNnRoTHA3blN6eUcwdmJpTApmZmZYeHBUdmJHajZkVmpab0U4QVVHWE5nMkoxWUtRVVlaSU53U2R5RWdZalNDSFlidTFLCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

    cert-manager.io/alt-names: '*.chaldea.cn'
    cert-manager.io/certificate-name: wildcard-chaldea-cn-tls
    cert-manager.io/common-name: '*.chaldea.cn'
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
    cert-manager.io/uri-sans: ""


traefik.toml
# traefik.toml
logLevel = "info"
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
      regex = "^http://(.*)"
      replacement = "https://$1"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/tls.crt"
      KeyFile = "/ssl/tls.key"
  [entryPoints.traefik]
  address = ":8080"
[ping]
entryPoint = "http"
[kubernetes]
[traefikLog]
  format = "json"
[api]
  entryPoint = "traefik"
  dashboard = true

