version: "3"
services: 
 rabbit1:
  image: "rabbitmq:3-management"
  restart: always
  hostname: "rabbit1"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq1"
  volumes:
    - rabbitmq_data:/etc/rabbitmq

volumes: 
  rabbitmq_data: