version: '3.5'

services:
    # db:
    #     image: postgres:13.1
    #     ports:
    #         - "5432:5432"
    #     restart: unless-stopped
    #     environment:
    #         - APP_PORT=22300
    #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #         - POSTGRES_USER=${POSTGRES_USER}
    #         - POSTGRES_DB=${POSTGRES_DATABASE}
    joplin:
        image: joplin/server:latest
        # depends_on:
        #     - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        environment:
            - APP_BASE_URL=http://192.168.50.151:22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=joplin
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=postgres

networks:
  default:
    external: true
    name: cluster