version: '3.5'

services:
  commsvr:
    container_name: commsvr
    image: docker.flexem.com/flexem-fbox/fbox.commsvr:1.75.0-dev.40-22da83
    ports: 
     - "39902:39902"
    restart: always
    volumes:
        - /opt/fbox/commsvr/firmware:/app/firmware
        - /opt/fbox/commsvr/LocalDb:/app/LocalDb
    environment:
      CorsOrigins__0: http://localhost:8100
      CorsOrigins__1: http://localhost:39801
      ConnectionStrings__Cs: "User ID=postgres;Password=postgres;Host=postgres;Port=5432;Database=fbcs;Pooling=true;"
      BoxConnection__NewProtocolServerList: tcp4://180.168.181.190:8157
      BoxConnection__DmonOnOffPushNowDelayConstant: 200
      BoxConnection__DmonOnOffPushNowDelayCoefficient: 2
      BoxConnection__NewVpnServer: "false"
      BoxConnection__IgnoreDevicePing: "true"
      AppSettings__CommServerId: "1"
      AppSettings__CommServerKey: b9a03779e3954d2b973128b12a2a076d
      AppSetting__DmonSyncWorkerWaitExtra: 500
      AppSetting__SyncAlarmItemOnStarted: "true"
      AppSettings__BoxMessageInitialConsumeOffset: End
      AppSettings__MaxBoxAsyncTaskInitializationDelay: 0
      AppSettings__MaxDmonStateSyncInterval: 9999999
      AppSettings__NewVpnCfgVersion: 6
      AppSettings__IdServerUrl: http://192.168.50.151:58491/core/
      AppSettings__CsAppServerUrl: http://appsvr:39901/api/cs/
      AppSettings__CsAppServerPushUrl: http://appsvr:39901/push/client/
      AppSettings__RsAppServerUrl: http://hdata:39702/api/rs/
      AppSettings__RsAppServerPushUrl: http://hdata:39702/push/client/
      AppSettings__CsPushServerUrl: http://push.fbox360.net/api/cs
      AppSettings__FileServerUrl: http://fbtest.fbox360.net/api/file/
      AppSettings__HdataServerUrl: http://fbhsd.fbox360.net/api/
      AppSettings__FirmwareServerUrl: http://defs.flexem.net/
      AppSettings__SmsServerUrl: http://sms.qa.fbox.flexem.net/api/sms/
      AppSettings__DisableSms: "false"
      AppSettings__ServerMode: Normal
      AppSettings__MaxPreloadedDataSources: 200000
      AppSettings__MaxPreloadedDmonDefs: 200000
      AppSettings__MaxPreloadedAlarmDefs: 200000
      AppSettings__MaxPreloadedContacts: 200000
      AppSettings__PreloadBatchSize: 20000
      AppSettings__HasSignalR: "false"
      AppSettings__DisableSignalR: "true"
      AppSettings__EnableDataPushToKafka: "true"
      AppSettings__UseSyncService: "true"
      AppSettings__VpnServerUrl: http://vpn.qa.fbox.flexem.net
      AppSettings__UseNewDataParser: "true"
      AppSettings__IgnoreDeviceHeadParse: "true"
      AppSettings__FileManagerServiceUrl: http://filemanager
      Kafka__GroupId: fbox-comm.server
      Kafka__ConsumerGroupId: fbox-comm.server
      Kafka__BootstrapServers: kafka:9092
      Kafka__TopicPrefix: fboxlocal.
      RocksDb__DataDir: LocalDb
      RocksDb__DefaultWriteOptions__Sync: "true"
      FileService__FileManagerServiceUrl: http://192.168.50.151:30007

networks:
  default:
    external: true
    name: cluster