version: '3.5'
services:
  appsvr:
    container_name: appsvr
    image: docker.flexem.com/flexem-fbox/fbox.appsvr:1.74.0.9-a137e6
    restart: always
    ports:
     - "39901:39901"
    environment:
      AppSettings__IdServerUrl: "http://192.168.50.151:58491/core/"
      AppSettings__IdServerApiBaseUrl: "http://identity:58491/api/"
      AppSettings__IdServerPushUrl: "http://identity:58491/push/"
      ConnectionStrings__As: "server=postgres;database=fbas;port=5432;user id=postgres;password=postgres;"
      Cassandra__ConnectionString: "Contact Points=192.168.50.77"
      Cassandra__Port: "34622"
      Kafka__BootstrapServers: "kafka:9092"
      Kafka__TopicPrefix: "fboxlocal."

networks:
  default:
    external: true
    name: cluster