version: "3.5"

services:
  gateway:
    container_name: gateway
    restart: always
    image: docker.flexem.com/flexem-fbox/fbox.gateway:1.0.0.1
    ports:
      - "30000:30000"
    volumes:
     - /opt/gateway/ocelot.json:/app/ocelot.json

networks:
  default:
    external: true
    name: cluster